// 搜索引擎配置
const SEARCH_ENGINES = {
    baidu: { url: 'https://www.baidu.com/s?wd=' },
    google: { url: 'https://www.google.com/search?q=' },
    bing: { url: 'https://www.bing.com/search?q=' }
};

const { login, fetchGroups, fetchLinks, createGroup, updateGroup, deleteGroup, createLink, updateLink, deleteLink, fetchWebInfo, fetchSettings, updateSettings, exportData, importData } = window.API;

const DEFAULT_ICON_DATA = encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect width="24" height="24" rx="12" fill="#4299e1" opacity="0.1"/><path fill="#4299e1" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z"/></svg>');

function saveSearchEngine(engine) { localStorage.setItem('preferred_search_engine', engine); }
function getSearchEngine() { return localStorage.getItem('preferred_search_engine') || 'baidu'; }

document.addEventListener('DOMContentLoaded', () => {
    const searchEngine = document.getElementById('searchEngine');
    searchEngine.value = getSearchEngine();
    checkLoginStatus();
    initializePage();
});

async function checkLoginStatus() {
    const token = getToken();
    if (token) {
        try {
            const response = await fetch(`${API_BASE_URL}/verify`, { headers: { 'Authorization': `Bearer ${token}` } });
            if (response.ok) { isAdmin = true; isEditMode = false; updateAdminButton(); } else { setToken(null); }
        } catch (error) { setToken(null); }
    }
}

async function initializePage() {
    try { const settings = await fetchSettings(); applySettings(settings || {}); } catch (e) {}
    await loadNavigation();
}

let isAdmin = false;
let isEditMode = false;

function updateAdminButton() {
    const adminButton = document.getElementById('adminButton');
    if (isAdmin) {
        if (isEditMode) {
            adminButton.innerHTML = `
                <button class="admin-button btn btn-danger" onclick="handleLogout()"><i class="fas fa-sign-out-alt"></i> 退出登录</button>
                <button class="admin-button btn btn-gray" onclick="exitEditMode()"><i class="fas fa-times"></i> 退出编辑</button>
            `;
        } else {
            adminButton.innerHTML = `
                <button class="admin-button btn btn-danger" onclick="handleLogout()"><i class="fas fa-sign-out-alt"></i> 退出登录</button>
                <button class="admin-button btn btn-primary" onclick="enterEditMode()"><i class="fas fa-edit"></i> 编辑</button>
            `;
        }
    } else {
        adminButton.innerHTML = `
            <button class="admin-button btn btn-primary" onclick="openAdminModal()"><i class="fas fa-user-lock"></i> 管理员登录</button>
        `;
    }
}

function enterEditMode() { isEditMode = true; updateAdminButton(); loadNavigation(); }
function exitEditMode() { isEditMode = false; updateAdminButton(); loadNavigation(); }
function handleLogout() { setToken(null); isAdmin = false; isEditMode = false; updateAdminButton(); loadNavigation(); }

function handleSearch(event) {
    event.preventDefault();
    const searchInput = document.getElementById('searchInput');
    const searchEngine = document.getElementById('searchEngine');
    const query = searchInput.value.trim();
    if (query) { const url = SEARCH_ENGINES[searchEngine.value].url + encodeURIComponent(query); window.open(url, '_blank'); }
    saveSearchEngine(searchEngine.value);
}

function openAdminModal() { document.getElementById('adminModal').style.display = 'block'; }
function closeAdminModal() { document.getElementById('adminModal').style.display = 'none'; }
async function handleLogin(event) { event.preventDefault(); const password = document.getElementById('adminPassword').value; try { await login(password); closeAdminModal(); isAdmin = true; updateAdminButton(); showToast('登录成功'); await loadNavigation(); } catch (error) { showToast('登录失败: ' + error.message, 'error'); } }

function openLinkModal(linkId = null) {
    if (!isEditMode) { showToast('请先登录管理员账号'); return; }
    const modal = document.getElementById('linkModal'); const form = document.getElementById('linkForm'); form.reset(); updateGroupSelect(); if (linkId) { loadLinkData(linkId); }
    const urlInput = document.getElementById('linkUrl'); urlInput.removeEventListener('blur', autoFillLinkInfo); urlInput.addEventListener('blur', autoFillLinkInfo);
    modal.style.display = 'block';
}
function closeLinkModal() { document.getElementById('linkModal').style.display = 'none'; }

async function handleLinkSubmit(event) {
    event.preventDefault();
    const linkId = event.target.dataset.linkId; const groupId = parseInt(document.getElementById('linkGroup').value);
    let orderNum;
    if (linkId) {
        const links = await fetchLinks(); const currentLink = links.find(l => l.id === parseInt(linkId));
        if (currentLink && currentLink.group_id !== groupId) {
            try {
                const oldGroupLinks = links.filter(l => l.group_id === currentLink.group_id).sort((a,b)=>a.order_num-b.order_num);
                for (let i=0;i<oldGroupLinks.length;i++){ const link=oldGroupLinks[i]; if (link.order_num > currentLink.order_num) { await updateLink(link.id,{...link,order_num:link.order_num-1}); } }
                const groupLinks = links.filter(l => l.group_id === groupId); groupLinks.sort((a,b)=>a.order_num-b.order_num); orderNum = groupLinks.length + 1;
            } catch (error) { showToast('更新序号失败: ' + error.message, 'error'); return; }
        } else { orderNum = parseInt(event.target.dataset.orderNum) || 0; }
    } else {
        try { const links = await fetchLinks(); const groupLinks = links.filter(l => l.group_id === groupId); const maxOrderNum = groupLinks.reduce((max, link) => Math.max(max, link.order_num || 0), 0); orderNum = maxOrderNum + 1; } catch (error) { orderNum = 1; }
    }
    const formData = { name: document.getElementById('linkName').value, url: document.getElementById('linkUrl').value, logo: document.getElementById('linkLogo').value, description: document.getElementById('linkDescription').value, group_id: groupId, order_num: orderNum };
    try { if (linkId) { await updateLink(parseInt(linkId), formData); } else { await createLink(formData); } closeLinkModal(); showToast('保存成功'); await loadNavigation(); } catch (error) { showToast('保存失败: ' + error.message, 'error'); }
}

function openGroupModal(groupId = null) { if (!isEditMode) { showToast('请先登录管理员账号'); return; } const modal = document.getElementById('groupModal'); const form = document.getElementById('groupForm'); form.reset(); form.dataset.groupId = groupId || ''; if (groupId) { loadGroupData(groupId); } modal.style.display='block'; }
function closeGroupModal() { document.getElementById('groupModal').style.display = 'none'; }
async function handleGroupSubmit(event) { event.preventDefault(); const groupId = event.target.dataset.groupId; const groups = await fetchGroups(); const maxOrderNum = Math.max(0, ...groups.map(g => g.order_num || 0)); const formData = { name: document.getElementById('groupName').value, is_private: document.getElementById('groupPrivate').checked, order_num: groupId ? parseInt(event.target.dataset.orderNum) || 0 : maxOrderNum + 1, bg_color: document.getElementById('groupBgColor') ? document.getElementById('groupBgColor').value.trim() || null : null, bg_image: document.getElementById('groupBgImage') ? document.getElementById('groupBgImage').value.trim() || null : null }; try { if (groupId) { await updateGroup(groupId, formData); } else { await createGroup(formData); } closeGroupModal(); showToast('分组保存成功'); await loadNavigation(); } catch (error) { showToast('保存失败: ' + error.message, 'error'); } }

const iconCache = new Map();
async function getIconUrl({ url }) { try { const domain = new URL(url).hostname; const cacheKey = `icon_cache_${domain}`; const cachedUrl = localStorage.getItem(cacheKey); if (cachedUrl) { return cachedUrl; } const iconUrls = [`https://icon.horse/icon/${domain}`, `https://api.faviconkit.com/${domain}/144`, `https://${domain}/favicon.ico`]; for (const iconUrl of iconUrls) { try { const img = new Image(); await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = iconUrl; }); localStorage.setItem(cacheKey, iconUrl); return iconUrl; } catch (error) { continue; } } return null; } catch (error) { return null; } }

async function loadNavigation() {
    const navigationElement = document.getElementById('navigation'); const groupNavElement = document.getElementById('groupNav');
    const loadingHtml = `<div class="nav-loading"><div class="nav-loading-dot"></div><div class="nav-loading-dot"></div><div class="nav-loading-dot"></div></div>`;
    navigationElement.innerHTML = `<div class="loading"><div class="loading-wave"><div></div><div></div></div><div>加载中...</div></div>`; groupNavElement.innerHTML = loadingHtml;
    try {
        const groups = await fetchGroups(); const links = await fetchLinks();
        let html = ''; let navHtml='';
        if (isEditMode) { html += `<div class="admin-controls"><button class="btn btn-primary" onclick="openGroupModal()"><i class="fas fa-folder-plus"></i> 添加分组</button><button class="btn btn-primary" onclick="openLinkModal()"><i class="fas fa-link"></i> 添加链接</button><button class="btn btn-accent" onclick="openSettingsModal()"><i class="fas fa-paint-roller"></i> 页面设置</button><button class="btn btn-accent" onclick="handleExport()"><i class="fas fa-download"></i> 导出数据</button><button class="btn btn-accent" onclick="triggerImport()"><i class="fas fa-upload"></i> 导入数据</button></div>`; }
        if (groups.length === 0) { navigationElement.innerHTML = html + '暂无内容'; groupNavElement.innerHTML = '暂无分组'; return; }
        for (const group of groups) {
            if (!group.is_private || isAdmin) {
                const groupLinks = links.filter(link => link.group_id === group.id); const groupId = `group-${group.id}`;
                html += `<div id="${groupId}" class="group" style="${getGroupStyle(group)}"><div class="group-title">${getGroupTitle(group)}${getGroupActions(group.id)}</div><div class="links">${groupLinks.map(link => getLinkCard(link)).join('')}</div></div>`;
                navHtml += `<a href="#${groupId}" class="nav-item" onclick="highlightNavItem(this)" data-group-id="${groupId}">${group.name}${group.is_private ? `<i class=\"fas fa-lock group-privacy-icon\" title=\"私密分组\"></i>` : ''}</a>`;
            }
        }
        navigationElement.innerHTML = html; groupNavElement.innerHTML = navHtml; await loadIcons(); window.addEventListener('scroll', updateActiveNavItem);
    } catch (error) { navigationElement.innerHTML = `<div class="error">加载失败: ${error.message}</div>`; groupNavElement.innerHTML = `<div class="error">加载失败</div>`; }
}

function highlightNavItem(element) { document.querySelectorAll('.nav-item').forEach(item => { item.classList.remove('active'); }); element.classList.add('active'); }
function updateActiveNavItem() { const groups = document.querySelectorAll('.group'); const navItems = document.querySelectorAll('.nav-item'); groups.forEach((group, index) => { const rect = group.getBoundingClientRect(); if (rect.top <= 100 && rect.bottom >= 100) { highlightNavItem(navItems[index]); } }); }

function createLinkCard(link) { const domain = new URL(link.url).hostname; const defaultIcon = `https://icon.horse/icon/${domain}`; return `<div class="link-card"><a href="${link.url}" target="_blank" class="link-content"><img class="link-icon" src="${link.logo || defaultIcon}" alt="" onerror="this.src='https://icon.horse/icon/example.com'"><div class="link-card-content"><div class="link-title">${link.name}</div>${link.description ? `<div class=\"link-description\">${link.description}</div>` : ''}</div></a><div class="link-url-tooltip">${link.url}</div>${isEditMode ? `<div class="link-actions"><button class="btn btn-primary" onclick="openLinkModal(${link.id})"><i class="fas fa-edit"></i> 编辑</button><button class="btn btn-danger" onclick="deleteLinkConfirm(${link.id})"><i class="fas fa-trash"></i> 删除</button><div class="order-actions"><button class="btn btn-gray" onclick="moveLinkUp(${link.id}, ${link.group_id})"><i class="fas fa-arrow-up"></i></button><button class="btn btn-gray" onclick="moveLinkDown(${link.id}, ${link.group_id})"><i class="fas fa-arrow-down"></i></button></div></div>` : ''}</div>`; }

function showToast(message, type = 'success') { const container = document.getElementById('toastContainer'); const toast = document.createElement('div'); toast.className = `toast ${type}`; let icon = ''; switch (type) { case 'success': icon = '<i class="fas fa-check-circle"></i>'; break; case 'error': icon = '<i class="fas fa-times-circle"></i>'; break; case 'loading': icon = '<i class="fas fa-spinner"></i>'; break; } toast.innerHTML = `${icon}${message}`; container.appendChild(toast); if (type !== 'loading') { setTimeout(() => { toast.remove(); }, 3000); } return toast; }
function showConfirm(title, message) { return new Promise((resolve) => { const dialog = document.getElementById('confirmDialog'); dialog.querySelector('.confirm-title').textContent = title; dialog.querySelector('.confirm-message').textContent = message; dialog.style.display = 'block'; const handleClick = (result) => { dialog.style.display = 'none'; resolve(result); }; dialog.querySelector('.confirm-ok').onclick = () => handleClick(true); dialog.querySelector('.confirm-cancel').onclick = () => handleClick(false); }); }
window.onclick = function(event) { const modal = document.getElementById('adminModal'); if (event.target === modal) { closeAdminModal(); } }
async function deleteGroupConfirm(groupId) { const confirmed = await showConfirm('删除分组','确定要删除这个分组吗？这将同时删除组内的所有链接！'); if (confirmed) { const toast = showToast('正在删除分组...', 'loading'); try { await deleteGroup(groupId); toast.remove(); showToast('分组删除成功'); await loadNavigation(); } catch (error) { toast.remove(); showToast('删除失败: ' + error.message, 'error'); } } }
async function loadGroupData(groupId) { try { const groups = await fetchGroups(); const group = groups.find(g => g.id === parseInt(groupId)); if (group) { document.getElementById('groupName').value = group.name; document.getElementById('groupPrivate').checked = group.is_private; const form = document.getElementById('groupForm'); form.dataset.groupId = groupId; form.dataset.orderNum = group.order_num; if (document.getElementById('groupBgColor')) { document.getElementById('groupBgColor').value = group.bg_color || ''; } if (document.getElementById('groupBgImage')) { document.getElementById('groupBgImage').value = group.bg_image || ''; } } } catch (error) { showToast('加载分组数据失败: ' + error.message, 'error'); } }
async function loadLinkData(linkId) { try { const links = await fetchLinks(); const link = links.find(l => l.id === linkId); if (link) { document.getElementById('linkName').value = link.name; document.getElementById('linkUrl').value = link.url; document.getElementById('linkLogo').value = link.logo || ''; document.getElementById('linkDescription').value = link.description || ''; document.getElementById('linkGroup').value = link.group_id; document.getElementById('linkForm').dataset.linkId = linkId; document.getElementById('linkForm').dataset.orderNum = link.order_num; } } catch (error) { showToast('加载链接数据失败: ' + error.message, 'error'); } }
async function updateGroupSelect() { const select = document.getElementById('linkGroup'); try { const groups = await fetchGroups(); select.innerHTML = '<option value="">选择分组...</option>' + groups.map(group => `<option value="${group.id}">${group.name}</option>`).join(''); } catch (error) {} }
async function deleteLinkConfirm(linkId) { const confirmed = await showConfirm('删除链接','确定要删除这个链接吗？'); if (confirmed) { const toast = showToast('正在删除链接...', 'loading'); try { await deleteLink(linkId); toast.remove(); showToast('链接删除成功'); await loadNavigation(); } catch (error) { toast.remove(); showToast('删除失败: ' + error.message, 'error'); } } }
async function moveLinkUp(linkId, groupId) { let toast; const links = (await fetchLinks()).filter(l => l.group_id === groupId); const currentIndex = links.findIndex(l => l.id === linkId); if (currentIndex === 0) { if (toast) toast.remove(); showToast('已经是第一个链接了', 'error'); return; } toast = showToast('正在更新顺序...', 'loading'); const currentLink = links[currentIndex]; const prevLink = links[currentIndex - 1]; try { const prevOrder = (prevLink.order_index != null ? prevLink.order_index : prevLink.order_num) || 0; const currOrder = (currentLink.order_index != null ? currentLink.order_index : currentLink.order_num) || 0; await updateLink(currentLink.id, { ...currentLink, order_num: prevOrder, order_index: prevOrder }); await updateLink(prevLink.id, { ...prevLink, order_num: currOrder, order_index: currOrder }); toast.remove(); showToast('链接顺序已更新'); await loadNavigation(); } catch (error) { toast.remove(); showToast('更新顺序失败: ' + error.message, 'error'); } finally { if (toast) toast.remove(); } }
async function moveLinkDown(linkId, groupId) { let toast; const links = (await fetchLinks()).filter(l => l.group_id === groupId); const currentIndex = links.findIndex(l => l.id === linkId); if (currentIndex === links.length - 1) { if (toast) toast.remove(); showToast('已经是最后一个链接了', 'error'); return; } toast = showToast('正在更新顺序...', 'loading'); const currentLink = links[currentIndex]; const nextLink = links[currentIndex + 1]; try { const nextOrder = (nextLink.order_index != null ? nextLink.order_index : nextLink.order_num) || 0; const currOrder = (currentLink.order_index != null ? currentLink.order_index : currentLink.order_num) || 0; await updateLink(currentLink.id, { ...currentLink, order_num: nextOrder, order_index: nextOrder }); await updateLink(nextLink.id, { ...nextLink, order_num: currOrder, order_index: currOrder }); toast.remove(); showToast('链接顺序已更新'); await loadNavigation(); } catch (error) { toast.remove(); showToast('更新顺序失败: ' + error.message, 'error'); } finally { if (toast) toast.remove(); } }
async function autoFillLinkInfo() { const urlInput = document.getElementById('linkUrl'); const nameInput = document.getElementById('linkName'); const logoInput = document.getElementById('linkLogo'); const descriptionInput = document.getElementById('linkDescription'); const url = urlInput.value.trim(); if (!url) return; const toast = showToast('正在获取网页信息...', 'loading'); try { const domain = new URL(url).hostname; const iconUrl = await getIconUrl({ url }); const info = await fetchWebInfo(url); if (!nameInput.value) { nameInput.value = info.title || ''; } if (!logoInput.value) { logoInput.value = iconUrl || ''; } if (!descriptionInput.value) { descriptionInput.value = info.description || ''; } toast.remove(); showToast('获取网页信息成功'); } catch (error) { toast.remove(); showToast('获取网页信息失败: ' + error.message, 'error'); } }
async function moveGroupUp(groupId) { let toast; const groups = await fetchGroups(); const currentIndex = groups.findIndex(g => g.id === groupId); if (currentIndex === 0) { if (toast) toast.remove(); showToast('已经是第一个分组了', 'error'); return; } toast = showToast('正在更新顺序...', 'loading'); const currentGroup = groups[currentIndex]; const prevGroup = groups[currentIndex - 1]; try { const prevOrder = (prevGroup.order_index != null ? prevGroup.order_index : prevGroup.order_num) || 0; const currOrder = (currentGroup.order_index != null ? currentGroup.order_index : currentGroup.order_num) || 0; await updateGroup(currentGroup.id, { ...currentGroup, order_num: prevOrder, order_index: prevOrder }); await updateGroup(prevGroup.id, { ...prevGroup, order_num: currOrder, order_index: currOrder }); toast.remove(); showToast('分组顺序已更新'); await loadNavigation(); } catch (error) { toast.remove(); showToast('更新顺序失败: ' + error.message, 'error'); } finally { if (toast) toast.remove(); } }
async function moveGroupDown(groupId) { let toast; const groups = await fetchGroups(); const currentIndex = groups.findIndex(g => g.id === groupId); if (currentIndex === groups.length - 1) { if (toast) toast.remove(); showToast('已经是最后一个分组了', 'error'); return; } toast = showToast('正在更新顺序...', 'loading'); const currentGroup = groups[currentIndex]; const nextGroup = groups[currentIndex + 1]; try { const nextOrder = (nextGroup.order_index != null ? nextGroup.order_index : nextGroup.order_num) || 0; const currOrder = (currentGroup.order_index != null ? currentGroup.order_index : currentGroup.order_num) || 0; await updateGroup(currentGroup.id, { ...currentGroup, order_num: nextOrder, order_index: nextOrder }); await updateGroup(nextGroup.id, { ...nextGroup, order_num: currOrder, order_index: currOrder }); toast.remove(); showToast('分组顺序已更新'); await loadNavigation(); } catch (error) { toast.remove(); showToast('更新顺序失败: ' + error.message, 'error'); } finally { if (toast) toast.remove(); } }
function getGroupActions(groupId) { if (!isEditMode) return ''; return `<div class="group-actions"><div class="order-actions"><button class="btn btn-gray" onclick="moveGroupUp(${groupId})" title="上移"><i class="fas fa-arrow-up"></i></button><button class="btn btn-gray" onclick="moveGroupDown(${groupId})" title="下移"><i class="fas fa-arrow-down"></i></button></div><button class="btn btn-primary" onclick="openGroupModal(${groupId})" title="编辑"><i class="fas fa-edit"></i></button><button class="btn btn-danger" onclick="deleteGroupConfirm(${groupId})" title="删除"><i class="fas fa-trash"></i></button></div>`; }
function getGroupTitle(group) { return `<div class="group-title-left">${group.name}${group.is_private ? `<i class=\"fas fa-lock group-privacy-icon\" title=\"私密分组\"></i>` : (isEditMode ? `<i class=\"fas fa-lock-open group-privacy-icon\" title=\"公开分组\"></i>` : '')}</div>`; }
function getLinkCard(link) { const iconSrc = link.logo || '#'; const defaultIcon = encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect width="24" height="24" rx="12" fill="#4299e1" opacity="0.1"/><path fill="#4299e1" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z"/></svg>`); return `<a href="${link.url}" target="_blank" class="link-card"><div class="link-info"><div class="link-icon"><img src="${iconSrc}" data-url="${link.url}" alt="${link.name}" ${!link.logo ? 'data-auto-icon="true"' : ''} onerror="this.onerror=null; this.src='data:image/svg+xml,${defaultIcon}';"></div><div class="link-text"><span class="link-title">${link.name}</span><div class="link-description">${link.description || ''}</div></div></div>${isEditMode ? `<div class="link-actions" onclick="event.preventDefault();"><div class="order-actions"><button class="btn btn-gray" onclick="moveLinkUp(${link.id}, ${link.group_id})" title="上移"><i class="fas fa-arrow-up"></i></button><button class="btn btn-gray" onclick="moveLinkDown(${link.id}, ${link.group_id})" title="下移"><i class="fas fa-arrow-down"></i></button></div><button class="btn btn-primary" onclick="openLinkModal(${link.id})" title="编辑"><i class="fas fa-edit"></i></button><button class="btn btn-danger" onclick="deleteLinkConfirm(${link.id})" title="删除"><i class="fas fa-trash"></i></button></div>` : ''}</a>`; }
function getFallbackIcon(url) { const domain = new URL(url).hostname.toLowerCase(); const iconMap = { 'github.com': 'github','youtube.com': 'youtube','twitter.com': 'twitter','facebook.com': 'facebook','instagram.com': 'instagram','linkedin.com': 'linkedin','medium.com': 'medium','reddit.com': 'reddit','stackoverflow.com': 'stack-overflow','amazon.com': 'amazon','google.com': 'google','microsoft.com': 'microsoft','apple.com': 'apple','netflix.com': 'netflix','spotify.com': 'spotify','twitch.tv': 'twitch','wikipedia.org': 'wikipedia-w','wordpress.com': 'wordpress','blogger.com': 'blogger','pinterest.com': 'pinterest' }; for (const [site, icon] of Object.entries(iconMap)) { if (domain.includes(site)) { return icon; } } if (domain.includes('docs.') || domain.endsWith('.doc')) return 'file-word'; if (domain.includes('sheets.') || domain.endsWith('.xls')) return 'file-excel'; if (domain.includes('slides.') || domain.endsWith('.ppt')) return 'file-powerpoint'; if (domain.includes('drive.') || domain.includes('cloud')) return 'cloud'; if (domain.includes('mail.') || domain.includes('outlook')) return 'envelope'; if (domain.includes('chat.') || domain.includes('meet.')) return 'comments'; if (domain.includes('map')) return 'map-marker-alt'; if (domain.includes('video') || domain.includes('tv')) return 'video'; if (domain.includes('music') || domain.includes('audio')) return 'music'; if (domain.includes('shop') || domain.includes('store')) return 'shopping-cart'; if (domain.includes('game')) return 'gamepad'; if (domain.includes('news')) return 'newspaper'; if (domain.includes('blog')) return 'blog'; return 'link'; }
async function loadIcons() { const icons = document.querySelectorAll('.link-icon img'); for (const img of icons) { if (img.dataset.autoIcon === 'true') { const url = img.dataset.url; if (url) { try { const iconUrl = await getIconUrl({ url }); if (iconUrl) { img.src = iconUrl; img.crossOrigin = 'anonymous'; } else { throw new Error('No icon found'); } } catch (error) { img.src = `data:image/svg+xml,${DEFAULT_ICON_DATA}`; } } } } }
function openSettingsModal() { if (!isEditMode) { showToast('请先登录管理员账号'); return; } const modal = document.getElementById('settingsModal'); const form = document.getElementById('settingsForm'); form.reset(); loadSettingsData(); modal.style.display = 'block'; }
function closeSettingsModal() { const modal = document.getElementById('settingsModal'); modal.style.display = 'none'; }
async function loadSettingsData() { try { const settings = await fetchSettings(); if (settings) { if (document.getElementById('pageBgColor')) document.getElementById('pageBgColor').value = settings.page_bg_color || ''; if (document.getElementById('pageBgImage')) document.getElementById('pageBgImage').value = settings.page_bg_image || ''; if (document.getElementById('navBgColor')) document.getElementById('navBgColor').value = settings.nav_bg_color || ''; if (document.getElementById('navBgImage')) document.getElementById('navBgImage').value = settings.nav_bg_image || ''; const t = settings.theme || {}; if (document.getElementById('themePrimary')) document.getElementById('themePrimary').value = t.primary || ''; if (document.getElementById('themePrimaryHover')) document.getElementById('themePrimaryHover').value = t.primaryHover || ''; if (document.getElementById('themeDanger')) document.getElementById('themeDanger').value = t.danger || ''; if (document.getElementById('themeGray')) document.getElementById('themeGray').value = t.gray || ''; if (document.getElementById('themeAccent')) document.getElementById('themeAccent').value = t.accent || ''; if (document.getElementById('themeAccentHover')) document.getElementById('themeAccentHover').value = t.accentHover || ''; if (document.getElementById('themeTextMain')) document.getElementById('themeTextMain').value = t.textMain || ''; if (document.getElementById('themeTextMuted')) document.getElementById('themeTextMuted').value = t.textMuted || ''; if (document.getElementById('themeBorder')) document.getElementById('themeBorder').value = t.border || ''; if (document.getElementById('themeNavActiveBg')) document.getElementById('themeNavActiveBg').value = t.navActiveBg || ''; if (document.getElementById('themeGroupGradientStart')) document.getElementById('themeGroupGradientStart').value = t.groupGradientStart || ''; if (document.getElementById('themeGroupGradientEnd')) document.getElementById('themeGroupGradientEnd').value = t.groupGradientEnd || ''; } } catch (e) {} }
async function handleSettingsSubmit(event) { event.preventDefault(); const data = { page_bg_color: document.getElementById('pageBgColor') ? document.getElementById('pageBgColor').value.trim() || null : null, page_bg_image: document.getElementById('pageBgImage') ? document.getElementById('pageBgImage').value.trim() || null : null, nav_bg_color: document.getElementById('navBgColor') ? document.getElementById('navBgColor').value.trim() || null : null, nav_bg_image: document.getElementById('navBgImage') ? document.getElementById('navBgImage').value.trim() || null : null, theme: { primary: document.getElementById('themePrimary') ? document.getElementById('themePrimary').value.trim() || null : null, primaryHover: document.getElementById('themePrimaryHover') ? document.getElementById('themePrimaryHover').value.trim() || null : null, danger: document.getElementById('themeDanger') ? document.getElementById('themeDanger').value.trim() || null : null, gray: document.getElementById('themeGray') ? document.getElementById('themeGray').value.trim() || null : null, accent: document.getElementById('themeAccent') ? document.getElementById('themeAccent').value.trim() || null : null, accentHover: document.getElementById('themeAccentHover') ? document.getElementById('themeAccentHover').value.trim() || null : null, textMain: document.getElementById('themeTextMain') ? document.getElementById('themeTextMain').value.trim() || null : null, textMuted: document.getElementById('themeTextMuted') ? document.getElementById('themeTextMuted').value.trim() || null : null, border: document.getElementById('themeBorder') ? document.getElementById('themeBorder').value.trim() || null : null, navActiveBg: document.getElementById('themeNavActiveBg') ? document.getElementById('themeNavActiveBg').value.trim() || null : null, groupGradientStart: document.getElementById('themeGroupGradientStart') ? document.getElementById('themeGroupGradientStart').value.trim() || null : null, groupGradientEnd: document.getElementById('themeGroupGradientEnd') ? document.getElementById('themeGroupGradientEnd').value.trim() || null : null } }; try { await updateSettings(data); closeSettingsModal(); showToast('设置已保存'); applySettings(data); } catch (error) { showToast('保存失败: ' + error.message, 'error'); } }
function applySettings(settings) { try { const body = document.body; if (settings.page_bg_image) { body.style.backgroundImage = `url(${settings.page_bg_image})`; body.style.backgroundSize = 'cover'; body.style.backgroundPosition = 'center'; body.style.backgroundRepeat = 'no-repeat'; } else if (settings.page_bg_color) { body.style.backgroundImage = ''; body.style.background = settings.page_bg_color; } const nav = document.querySelector('.nav-sidebar'); if (nav) { if (settings.nav_bg_image) { nav.style.backgroundImage = `url(${settings.nav_bg_image})`; nav.style.backgroundSize = 'cover'; nav.style.backgroundPosition = 'center'; nav.style.backgroundRepeat = 'no-repeat'; } else if (settings.nav_bg_color) { nav.style.backgroundImage = ''; nav.style.background = settings.nav_bg_color; } } const t = settings.theme || {}; const root = document.documentElement; if (t.primary) root.style.setProperty('--color-primary', t.primary); if (t.primaryHover) root.style.setProperty('--color-primary-hover', t.primaryHover); if (t.danger) root.style.setProperty('--color-danger', t.danger); if (t.gray) root.style.setProperty('--color-gray', t.gray); if (t.accent) root.style.setProperty('--color-accent', t.accent); if (t.accentHover) root.style.setProperty('--color-accent-hover', t.accentHover); if (t.textMain) root.style.setProperty('--text-main', t.textMain); if (t.textMuted) root.style.setProperty('--text-muted', t.textMuted); if (t.border) root.style.setProperty('--border-color', t.border); if (t.navActiveBg) root.style.setProperty('--nav-active-bg', t.navActiveBg); if (t.groupGradientStart) root.style.setProperty('--group-gradient-start', t.groupGradientStart); if (t.groupGradientEnd) root.style.setProperty('--group-gradient-end', t.groupGradientEnd); } catch (e) {} }
function getGroupStyle(group) { const color = group.bg_color || ''; const image = group.bg_image || ''; if (image) { return `background-image:url(${image});background-size:cover;background-position:center;`; } if (color) { return `background:${color};`; } return ''; }

async function handleExport() { const toast = showToast('正在导出...', 'loading'); try { const data = await exportData(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); const ts = new Date(); const pad = (n)=>String(n).padStart(2,'0'); const name = `mypage-export-${ts.getFullYear()}${pad(ts.getMonth()+1)}${pad(ts.getDate())}-${pad(ts.getHours())}${pad(ts.getMinutes())}${pad(ts.getSeconds())}.json`; a.href = URL.createObjectURL(blob); a.download = name; document.body.appendChild(a); a.click(); a.remove(); toast.remove(); showToast('导出完成'); } catch (e) { toast.remove(); showToast('导出失败: ' + e.message, 'error'); } }
function triggerImport() { const input = document.createElement('input'); input.type = 'file'; input.accept = 'application/json'; input.onchange = async () => { const file = input.files[0]; if (!file) return; const toast = showToast('正在导入...', 'loading'); try { const text = await file.text(); const payload = JSON.parse(text); await importData(payload); toast.remove(); showToast('导入完成'); await loadNavigation(); } catch (e) { toast.remove(); showToast('导入失败: ' + e.message, 'error'); } }; input.click(); }